2021-08-18 14:00:20,333 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 14:00:20,334 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:00:20,334 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:00:20,335 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '1752d2f0785658c328f0ed6d6c0bc7debd495d9c'}
2021-08-18 14:00:20,335 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:00:20,335 INFO    MainThread:64 [wandb_init.py:_log_setup():342] Logging user logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140020-13eotdsv/logs/debug.log
2021-08-18 14:00:20,336 INFO    MainThread:64 [wandb_init.py:_log_setup():343] Logging internal logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140020-13eotdsv/logs/debug-internal.log
2021-08-18 14:00:20,337 INFO    MainThread:64 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>
2021-08-18 14:00:20,342 INFO    MainThread:64 [wandb_init.py:init():375] calling init triggers
2021-08-18 14:00:20,344 INFO    MainThread:64 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-18 14:00:20,344 INFO    MainThread:64 [wandb_init.py:init():397] re-initializing run, found existing run on stack: gj5r3nny
2021-08-18 14:00:20,350 INFO    MainThread:64 [wandb_run.py:finish():1254] finishing run lesterye/OCR-Project/gj5r3nny
2021-08-18 14:00:20,357 INFO    MainThread:64 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 14:00:20,359 INFO    MainThread:64 [wandb_run.py:_restore():1526] restore
2021-08-18 14:00:21,144 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 813
  total_bytes: 813
}

2021-08-18 14:00:21,383 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 813
  total_bytes: 8292
}

2021-08-18 14:00:21,488 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 841
  total_bytes: 18255
}

2021-08-18 14:00:21,592 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18255
  total_bytes: 18255
}

2021-08-18 14:00:21,696 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18255
  total_bytes: 18255
}

2021-08-18 14:00:21,799 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18255
  total_bytes: 18255
}

2021-08-18 14:00:21,948 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18255
  total_bytes: 18255
}

2021-08-18 14:00:22,051 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 18255
  total_bytes: 18255
}

2021-08-18 14:00:23,505 INFO    MainThread:64 [wandb_run.py:_show_files():1898] logging synced files
2021-08-18 14:00:23,520 INFO    MainThread:64 [wandb_init.py:init():424] starting backend
2021-08-18 14:00:23,521 INFO    MainThread:64 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-18 14:00:23,530 INFO    MainThread:64 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 14:00:23,538 INFO    MainThread:64 [backend.py:ensure_launched():140] started backend process with pid: 1174
2021-08-18 14:00:23,541 INFO    MainThread:64 [wandb_init.py:init():429] backend started and connected
2021-08-18 14:00:23,585 INFO    MainThread:64 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 14:00:25,739 INFO    MainThread:64 [wandb_init.py:init():477] updated telemetry
2021-08-18 14:00:25,740 INFO    MainThread:64 [wandb_init.py:init():500] communicating current version
2021-08-18 14:00:25,813 INFO    MainThread:64 [wandb_init.py:init():505] got version response 
2021-08-18 14:00:25,813 INFO    MainThread:64 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 14:00:25,889 INFO    MainThread:64 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 14:00:27,614 INFO    MainThread:64 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 14:00:27,623 INFO    MainThread:64 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 14:00:27,623 INFO    MainThread:64 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 14:00:27,625 INFO    MainThread:64 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 14:00:27,629 INFO    MainThread:64 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 14:00:27,649 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:00:27,650 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:00:27,659 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:00:27,686 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:00:27,686 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:00:57,511 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:07:37,204 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:07:37,204 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:07:45,440 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:07:45,469 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:07:45,469 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:10:49,760 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:10:50,413 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:10:50,413 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:11:43,765 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:11:43,793 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:11:43,794 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:11:50,849 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:11:53,491 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:11:53,492 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:12:32,899 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:33:58,947 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:33:58,947 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:34:07,159 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:34:16,114 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:34:16,116 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:34:22,149 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:34:22,173 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:34:22,173 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:34:30,174 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:34:34,935 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:34:34,936 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:34:34,961 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:34:34,980 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:34:34,981 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:34:58,724 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:34:58,745 INFO    MainThread:64 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 14:34:58,746 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 14:35:03,239 INFO    MainThread:64 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-18 14:35:03,480 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 14:35:03,482 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:35:03,482 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:35:03,482 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '1752d2f0785658c328f0ed6d6c0bc7debd495d9c'}
2021-08-18 14:35:03,483 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:35:03,484 INFO    MainThread:64 [wandb_init.py:_log_setup():342] Logging user logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_143503-jtnsct2p/logs/debug.log
2021-08-18 14:35:03,484 INFO    MainThread:64 [wandb_init.py:_log_setup():343] Logging internal logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_143503-jtnsct2p/logs/debug-internal.log
2021-08-18 14:35:03,486 INFO    MainThread:64 [wandb_init.py:init():375] calling init triggers
2021-08-18 14:35:03,486 INFO    MainThread:64 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-18 14:35:03,486 INFO    MainThread:64 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 13eotdsv
2021-08-18 14:35:03,489 INFO    MainThread:64 [wandb_run.py:finish():1254] finishing run lesterye/OCR-Project/13eotdsv
