2021-08-18 13:55:08,181 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 13:55:08,182 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 13:55:08,182 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 13:55:08,182 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '1752d2f0785658c328f0ed6d6c0bc7debd495d9c'}
2021-08-18 13:55:08,182 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 13:55:08,182 INFO    MainThread:64 [wandb_init.py:_log_setup():342] Logging user logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_135508-gj5r3nny/logs/debug.log
2021-08-18 13:55:08,183 INFO    MainThread:64 [wandb_init.py:_log_setup():343] Logging internal logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_135508-gj5r3nny/logs/debug-internal.log
2021-08-18 13:55:08,184 INFO    MainThread:64 [wandb_init.py:init():375] calling init triggers
2021-08-18 13:55:08,184 INFO    MainThread:64 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-18 13:55:08,184 INFO    MainThread:64 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 2j7u8av5
2021-08-18 13:55:08,186 INFO    MainThread:64 [wandb_run.py:finish():1254] finishing run lesterye/OCR-Project/2j7u8av5
2021-08-18 13:55:08,189 INFO    MainThread:64 [jupyter.py:save_history():339] not saving jupyter history
2021-08-18 13:55:08,189 INFO    MainThread:64 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 13:55:08,190 INFO    MainThread:64 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-18 13:55:08,191 INFO    MainThread:64 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 13:55:08,192 INFO    MainThread:64 [wandb_run.py:_restore():1526] restore
2021-08-18 13:55:08,550 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 623
  total_bytes: 623
}

2021-08-18 13:55:08,751 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 623
  total_bytes: 623
}

2021-08-18 13:55:09,114 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 623
  total_bytes: 420116
}

2021-08-18 13:55:09,225 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 997
  total_bytes: 420116
}

2021-08-18 13:55:09,328 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 420116
  total_bytes: 420116
}

2021-08-18 13:55:09,432 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 420116
  total_bytes: 420116
}

2021-08-18 13:55:09,534 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 420116
  total_bytes: 420116
}

2021-08-18 13:55:09,809 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 420116
  total_bytes: 420116
}

2021-08-18 13:55:09,912 INFO    MainThread:64 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 420116
  total_bytes: 420116
}

2021-08-18 13:55:11,353 INFO    MainThread:64 [wandb_run.py:_show_files():1898] logging synced files
2021-08-18 13:55:11,372 INFO    MainThread:64 [wandb_init.py:init():424] starting backend
2021-08-18 13:55:11,374 INFO    MainThread:64 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-18 13:55:11,381 INFO    MainThread:64 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 13:55:11,389 INFO    MainThread:64 [backend.py:ensure_launched():140] started backend process with pid: 997
2021-08-18 13:55:11,391 INFO    MainThread:64 [wandb_init.py:init():429] backend started and connected
2021-08-18 13:55:11,460 INFO    MainThread:64 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 13:55:16,478 INFO    MainThread:64 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 13:55:16,479 INFO    MainThread:64 [wandb_init.py:init():477] updated telemetry
2021-08-18 13:55:16,479 INFO    MainThread:64 [wandb_init.py:init():500] communicating current version
2021-08-18 13:55:16,553 INFO    MainThread:64 [wandb_init.py:init():505] got version response 
2021-08-18 13:55:16,554 INFO    MainThread:64 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 13:55:16,637 INFO    MainThread:64 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 13:55:18,236 INFO    MainThread:64 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 13:55:18,253 INFO    MainThread:64 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 13:55:18,253 INFO    MainThread:64 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 13:55:18,269 INFO    MainThread:64 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 13:55:18,269 INFO    MainThread:64 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 14:00:20,333 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 14:00:20,334 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:00:20,334 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:00:20,335 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '1752d2f0785658c328f0ed6d6c0bc7debd495d9c'}
2021-08-18 14:00:20,335 INFO    MainThread:64 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 14:00:20,335 INFO    MainThread:64 [wandb_init.py:_log_setup():342] Logging user logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140020-13eotdsv/logs/debug.log
2021-08-18 14:00:20,336 INFO    MainThread:64 [wandb_init.py:_log_setup():343] Logging internal logs to /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140020-13eotdsv/logs/debug-internal.log
2021-08-18 14:00:20,337 INFO    MainThread:64 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>
2021-08-18 14:00:20,342 INFO    MainThread:64 [wandb_init.py:init():375] calling init triggers
2021-08-18 14:00:20,344 INFO    MainThread:64 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-08-18 14:00:20,344 INFO    MainThread:64 [wandb_init.py:init():397] re-initializing run, found existing run on stack: gj5r3nny
2021-08-18 14:00:20,350 INFO    MainThread:64 [wandb_run.py:finish():1254] finishing run lesterye/OCR-Project/gj5r3nny
